name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          cd /home/tylerlisk/flask-todo-app || exit
          git pull origin main || exit
          python3 -m venv venv || exit
          source venv/bin/activate || exit
          pip install -r requirements.txt || exit
          sudo systemctl restart flask-todo-app.service || exit
        EOF
